// Code generated by sqlc. DO NOT EDIT.
// source: clients_get.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getClient = `-- name: GetClient :one
SELECT id, client_name, secret_hash, owner_id, client_category, client_desc, banner_picture_id, icon_id, redirect_uris, terms_url, privacy_policy_url, flag FROM clients WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetClient(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.queryRow(ctx, q.getClientStmt, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.SecretHash,
		&i.OwnerID,
		&i.ClientCategory,
		&i.ClientDesc,
		&i.BannerPictureID,
		&i.IconID,
		&i.RedirectUris,
		&i.TermsUrl,
		&i.PrivacyPolicyUrl,
		&i.Flag,
	)
	return i, err
}
