// Code generated by sqlc. DO NOT EDIT.
// source: clients_delete.sql

package db

import (
	"context"
)

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients WHERE
    id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id []byte) error {
	_, err := q.exec(ctx, q.deleteClientStmt, deleteClient, id)
	return err
}
