// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Client struct {
	ID               uuid.UUID      `json:"id"`
	ClientName       string         `json:"clientName"`
	SecretHash       string         `json:"secretHash"`
	OwnerID          uuid.UUID      `json:"ownerID"`
	ClientCategory   string         `json:"clientCategory"`
	ClientDesc       string         `json:"clientDesc"`
	BannerPictureID  uuid.UUID      `json:"bannerPictureID"`
	IconID           uuid.UUID      `json:"iconID"`
	RedirectUris     sql.NullString `json:"redirectUris"`
	TermsUrl         sql.NullString `json:"termsUrl"`
	PrivacyPolicyUrl sql.NullString `json:"privacyPolicyUrl"`
	Flag             sql.NullInt32  `json:"flag"`
}

type Password struct {
	ID       uuid.UUID `json:"id"`
	OwnerID  uuid.UUID `json:"ownerID"`
	PassHash string    `json:"passHash"`
	Revoked  bool      `json:"revoked"`
}

type Picture struct {
	ID       uuid.UUID `json:"id"`
	DescText string    `json:"descText"`
	FileSize int32     `json:"fileSize"`
	Width    int32     `json:"width"`
	Height   int32     `json:"height"`
}

type Token struct {
	ID          uuid.UUID `json:"id"`
	OwnerID     uuid.UUID `json:"ownerID"`
	ClientID    uuid.UUID `json:"clientID"`
	ExpiredAt   time.Time `json:"expiredAt"`
	Revoked     bool      `json:"revoked"`
	DeviceName  string    `json:"deviceName"`
	CountryName string    `json:"countryName"`
	LastAccess  time.Time `json:"lastAccess"`
}

type User struct {
	ID         uuid.UUID `json:"id"`
	Email      string    `json:"email"`
	PictureID  uuid.UUID `json:"pictureID"`
	GivenName  string    `json:"givenName"`
	FamilyName string    `json:"familyName"`
	Gender     string    `json:"gender"`
	Birthdate  time.Time `json:"birthdate"`
	Flag       int32     `json:"flag"`
}
