// Code generated by sqlc. DO NOT EDIT.
// source: passwords_create.sql

package db

import (
	"context"
)

const createPassword = `-- name: CreatePassword :exec
INSERT INTO passwords (
    id,
    owner_id,
    pass_hash
) VALUES (
    $1,
    $2,
    $3
)
`

type CreatePasswordParams struct {
	ID       []byte `json:"id"`
	OwnerID  []byte `json:"ownerID"`
	PassHash string `json:"passHash"`
}

func (q *Queries) CreatePassword(ctx context.Context, arg CreatePasswordParams) error {
	_, err := q.exec(ctx, q.createPasswordStmt, createPassword, arg.ID, arg.OwnerID, arg.PassHash)
	return err
}
