// Code generated by sqlc. DO NOT EDIT.
// source: passwords_revoke.sql

package db

import (
	"context"
)

const revokePassword = `-- name: RevokePassword :exec
UPDATE passwords SET
    revoked = 'true'
WHERE
    owner_id = $1 AND
    revoked = 'false'
`

func (q *Queries) RevokePassword(ctx context.Context, ownerID string) error {
	_, err := q.exec(ctx, q.revokePasswordStmt, revokePassword, ownerID)
	return err
}
