// Code generated by sqlc. DO NOT EDIT.
// source: passwords_get_by_user.sql

package db

import (
	"context"
)

const getPasswordByUserID = `-- name: GetPasswordByUserID :one
SELECT id, owner_id, pass_hash, revoked FROM passwords WHERE
    owner_id = $1
LIMIT 1
`

func (q *Queries) GetPasswordByUserID(ctx context.Context, ownerID string) (Password, error) {
	row := q.queryRow(ctx, q.getPasswordByUserIDStmt, getPasswordByUserID, ownerID)
	var i Password
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.PassHash,
		&i.Revoked,
	)
	return i, err
}
