// Code generated by sqlc. DO NOT EDIT.
// source: pictures_update.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const updatePicture = `-- name: UpdatePicture :exec
UPDATE pictures SET
    desc_text = $2,
    file_size = $3,
    width = $4,
    height = $5
WHERE
    id = $1
`

type UpdatePictureParams struct {
	ID       uuid.UUID `json:"id"`
	DescText string    `json:"descText"`
	FileSize int32     `json:"fileSize"`
	Width    int32     `json:"width"`
	Height   int32     `json:"height"`
}

func (q *Queries) UpdatePicture(ctx context.Context, arg UpdatePictureParams) error {
	_, err := q.exec(ctx, q.updatePictureStmt, updatePicture,
		arg.ID,
		arg.DescText,
		arg.FileSize,
		arg.Width,
		arg.Height,
	)
	return err
}
