// Code generated by sqlc. DO NOT EDIT.
// source: pictures_delete.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deletePicture = `-- name: DeletePicture :exec
DELETE FROM pictures WHERE
    id = $1
`

func (q *Queries) DeletePicture(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deletePictureStmt, deletePicture, id)
	return err
}
