// Code generated by sqlc. DO NOT EDIT.
// source: pictures_list.sql

package db

import (
	"context"
)

const listPictures = `-- name: ListPictures :many
SELECT id, desc_text, file_size, width, height FROM pictures
LIMIT $1 OFFSET $2
`

type ListPicturesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPictures(ctx context.Context, arg ListPicturesParams) ([]Picture, error) {
	rows, err := q.query(ctx, q.listPicturesStmt, listPictures, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Picture
	for rows.Next() {
		var i Picture
		if err := rows.Scan(
			&i.ID,
			&i.DescText,
			&i.FileSize,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
