// Code generated by sqlc. DO NOT EDIT.
// source: pictures_get.sql

package db

import (
	"context"
)

const getPicture = `-- name: GetPicture :one
SELECT id, desc_text, file_size, width, height FROM pictures WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetPicture(ctx context.Context, id []byte) (Picture, error) {
	row := q.queryRow(ctx, q.getPictureStmt, getPicture, id)
	var i Picture
	err := row.Scan(
		&i.ID,
		&i.DescText,
		&i.FileSize,
		&i.Width,
		&i.Height,
	)
	return i, err
}
