// Code generated by sqlc. DO NOT EDIT.
// source: tokens_revoke_all_by_user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const revokeAllTokensByUserID = `-- name: RevokeAllTokensByUserID :exec
UPDATE passwords SET
    revoked = 'true'
WHERE
    owner_id = $1 AND
    revoked = 'false'
`

func (q *Queries) RevokeAllTokensByUserID(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.exec(ctx, q.revokeAllTokensByUserIDStmt, revokeAllTokensByUserID, ownerID)
	return err
}
