// Code generated by sqlc. DO NOT EDIT.
// source: tokens_get_by_user.sql

package db

import (
	"context"
)

const getTokenByUserID = `-- name: GetTokenByUserID :one
SELECT id, owner_id, client_id, expired_at, revoked, device_name, country_name, last_access FROM tokens WHERE
    owner_id = $1
LIMIT 1
`

func (q *Queries) GetTokenByUserID(ctx context.Context, ownerID []byte) (Token, error) {
	row := q.queryRow(ctx, q.getTokenByUserIDStmt, getTokenByUserID, ownerID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ClientID,
		&i.ExpiredAt,
		&i.Revoked,
		&i.DeviceName,
		&i.CountryName,
		&i.LastAccess,
	)
	return i, err
}
