// Code generated by sqlc. DO NOT EDIT.
// source: users_get_by_email.sql

package db

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, picture_id, given_name, family_name, gender, birthdate, flag FROM users WHERE
    email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PictureID,
		&i.GivenName,
		&i.FamilyName,
		&i.Gender,
		&i.Birthdate,
		&i.Flag,
	)
	return i, err
}
