// Code generated by sqlc. DO NOT EDIT.
// source: users_get.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUser = `-- name: GetUser :one
SELECT id, email, picture_id, given_name, family_name, gender, birthdate, flag FROM users WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PictureID,
		&i.GivenName,
		&i.FamilyName,
		&i.Gender,
		&i.Birthdate,
		&i.Flag,
	)
	return i, err
}
