// Code generated by sqlc. DO NOT EDIT.
// source: users_update.sql

package db

import (
	"context"
	"time"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    email = $2,
    picture_id = $3,
    given_name = $4,
    family_name = $5,
    gender = $6,
    birthdate = $7,
    flag = $8
WHERE
    id = $1
`

type UpdateUserParams struct {
	ID         string    `json:"id"`
	Email      string    `json:"email"`
	PictureID  string    `json:"pictureID"`
	GivenName  string    `json:"givenName"`
	FamilyName string    `json:"familyName"`
	Gender     string    `json:"gender"`
	Birthdate  time.Time `json:"birthdate"`
	Flag       int32     `json:"flag"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.exec(ctx, q.updateUserStmt, updateUser,
		arg.ID,
		arg.Email,
		arg.PictureID,
		arg.GivenName,
		arg.FamilyName,
		arg.Gender,
		arg.Birthdate,
		arg.Flag,
	)
	return err
}
