// Code generated by sqlc. DO NOT EDIT.
// source: users_create.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    email,
    picture_id,
    given_name,
    family_name,
    gender,
    birthdate,
    flag
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type CreateUserParams struct {
	ID         string    `json:"id"`
	Email      string    `json:"email"`
	PictureID  string    `json:"pictureID"`
	GivenName  string    `json:"givenName"`
	FamilyName string    `json:"familyName"`
	Gender     string    `json:"gender"`
	Birthdate  time.Time `json:"birthdate"`
	Flag       int32     `json:"flag"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.exec(ctx, q.createUserStmt, createUser,
		arg.ID,
		arg.Email,
		arg.PictureID,
		arg.GivenName,
		arg.FamilyName,
		arg.Gender,
		arg.Birthdate,
		arg.Flag,
	)
	return err
}
